source 'https://github.com/DoNewsCode/DNSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'DNPageScrollView_Example' do
  pod 'DNPageScrollView', :path => '../'
  target 'DNPageScrollView_Tests' do
    inherit! :search_paths

    
  end
end
